### ISSUE TITLE
[Feat] (iOS) 카드 생성 화면 만들기

### ISSUE THREAD

**Issue by Jinsujin** [SangHwi-Back/todo-list#12]
## 💡 issue

[Feat] (iOS) 카드 생성 화면 만들기

## 📝 todo

- [ ] 카드 생성을 위한 모달 창 뷰를 xib 이용하여 구현한다.
- [ ] 모달창의 커스텀 클래스를 생성한다.
- [ ] 모달창에서 수행할 카드 액션 타입을 선언한다. (CardData 타입 안에서)
