### ISSUE TITLE
[FEAT] (BE) 보드 화면 조회하기

### ISSUE THREAD

**Issue by leejohy-0223** [SangHwi-Back/todo-list#14]
## 💡 issue
보드 화면 조회를 구현한다.

## 📝 todo
- [ ] 최초 화면 조회 시 임시 세션을 만들고, 클라이언트에 전달한다.
- [ ] 이후 조회 요청이 오게 되면, 세션 id를 통해 DB에서 조회된 내용을 반환한다.
- [ ] 조회는 우선 생성 시간을 기준으로 sorting해서 전달한다.

**Comment by leejohy-0223** [comment]
issue 13(CRUD)으로 함께 묶어서 진행하고자 close 처리하였습니다.
