### ISSUE TITLE
[Feat] (iOS) 서버응답 결과가 성공이라면 화면 갱신, 실패라면 alert 띄우기

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/todo-list#19]
## 💡 issue

[Feat] (iOS) 서버응답 결과가 성공이라면 화면 갱신, 실패라면 alert 띄우기

## 📝 todo

- [ ] 서버 응답 결과가 성공일 경우는 화면을 갱신하도록 한다.
- [ ] 서버 응답이 실패라면 UIAlertController를 이용한 알럿창을 띄우도록 한다.
- [ ] 뷰 컨트롤러에 결과 전달은 NotificationCenter를 이용한다.
