### ISSUE TITLE
[Feat] (iOS) 서버에서 보드 정보를 가져와 화면 업데이트

### ISSUE THREAD

**Issue by Jinsujin** [SangHwi-Back/todo-list#23]
## 💡 issue

보드 정보 API 를 호출해 화면 업데이트

## 📝 todo
- [x] API 호출 클래스를 테스트 가능하도록 모듈화하기
- [x] `Test` /todolist API 테스트  (추정시간: 1h)
- [x] 최초 화면 호출 후 화면 업데이트 (추정시간: 1h)
- [ ] 화면 업데이트 호출 실패시 alert 을 띄운다 (추정시간: 1h)

## 호출할 API
1. 모든 보드의 카드 리스트를 호출
    - 최초화면 업뎃
    - 사용자 정보를 담아서 API 호출
2. 각 보드의 카드 리스트 호출
