### ISSUE TITLE
[Feat] (iOS) CoreData 로 데이터 저장하기

### ISSUE THREAD

**Issue by Jinsujin** [SangHwi-Back/todo-list#24]
## 💡 issue

API 에서 받아온 데이터를 CoreData 에 저장해 활용한다.

## 📝 todo
- [x] 프로젝트에 CoreData 적용(추정시간: 4h)
  - 서버에서 데이터를 받아와 저장하여 활용
  - 서버 접속 실패시 이 데이터를 사용한다
- [ ] CoreData  데이터 저장 (추정시간: 2h)
  -  서버에서 받아온 JSON 데이터를 내부에 저장
- [ ] CoreData 에서 데이터 수정 (추정시간: 1h)
  -  카드 수정, 삭제시 받아온 서버의 응답을 이용해 CoreData 수정
