### ISSUE TITLE
[Test] (iOS) CoreData 데이터 읽기, 쓰기, 삭제

### ISSUE THREAD

**Issue by Jinsujin** [SangHwi-Back/todo-list#25]
## 💡 issue

CoreData 테스트

## 📝 todo
- [ ] CoreData 데이터 읽기 테스트
- [ ] CoreData 데이터 쓰기 테스트
- [ ] CoreData 데이터 삭제 테스트
