### ISSUE TITLE
[Feat](BE) User 기능 구현

### ISSUE THREAD

**Issue by leejohy-0223** [SangHwi-Back/todo-list#36]
## 💡 issue
Login 까지는 아니더라도, 클라이언트를 구분할 수 있는 식별자를 제공한다.

## 📝 todo
- [x] Set-Cookie 또는 API를 통해 클라이언트에 특정 Id값을 전달한다.
- [x] parameter 또는 Request Header의 쿠키를 통해 클라이언트에서 요청 시 해당 값을 항상 가져오도록 적용한다.
- [x] 헤더 검증 또는 파라미터 검증을 통해 정상적으로 요청하는지 검증한다.
