### ISSUE TITLE
[FEAT] (iOS) 네트워크 요청 모듈 생성

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/todo-list#4]
## 💡 Issue

네트워크만 담당하는 모델을 따로 생성한다.

## 📝 Tasks

- [x] 네트워크 요청 기능만 담당하는 모델 클래스(혹은 구조체)를 생성한다.
- [x] 네트워크로 전달받은 Data 객체를 처리하고 반환하는 클래스(혹은 구조체)를 따로 구현한다.

## 🧑‍🏭 Supplement

- [ ] Repository 역할을 하는 클래스를 만든다. 만들게 된다면 ViewController는 Repository 클래스랑만 소통한다.
- [ ] 간단히 네트워크를 통해 데이터를 가져올 수 있는 DB가 있다면 찾아서 구현하고 네트워크 테스트를 해본다.

**Comment by SangHwi-Back** [comment]
## Supplementary 에 관한 내용

1. Repository 구조까지 구현하기엔 아직 요구사항이 크지 않아서 구현하지 않기로 하였습니다.
2. NodeJS+MongoDB 관련 내용이 생각 났으나 아직 구현하기엔 공부가 많이 필요해서 중지하였습니다.
