### ISSUE TITLE
[Hotfix](BE) 2차 PR 반영

### ISSUE THREAD

**Issue by leejohy-0223** [SangHwi-Back/todo-list#40]
## 💡 issue
2차 PR 수정 제의 받은 부분에 대해 수정한다.

## 📝 todo
- [x] 고정된 userId를 지정하는 방식을, client에서 받도록 수정한다.
- [x] Map 형식의 CardInformationDto를 DTO로 감싸서 반환하도록 수정한다.
- [x] 카드 생성 시 상태 코드 200(OK)을 201(CREATED)로 수정한다.
- [x] schema.sql에서 update CASCADE를 제거한다.
