### ISSUE TITLE
[Refactor] (iOS) PR Comments 소스 반영

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/todo-list#48]
## 💡 issue

[Refactor] (iOS) PR Comments 소스 반영

## 📝 todo

- [x] .gitignore 파일 수정
- [x] ColumnTableViewManagement 이름은 너무 광범위하여 Wrapper 등 다른 이름을 사용해서 명확한 네이밍을 완성해보기.
- [x] reloadAllLabels 메소드의 이름은 명확하지 않음. 네이밍 수정 필요.
- [x] setDataSource 부분 수정필요
       검증 부분은 따로 분리 필요.
       모든 데이터를 바꾸는 부분, 특정 인덱스만 바꾸는 부분이라면 set/insert로 의미를 구분해서 사용할 필요가 있음.
- [x] CardDataMiddleWare의 초기화 메소드에 DataTask를 초기화 하는 부분을 클로저로 대체하여 클래스를 testable하게 바꿔보기.
