### ISSUE TITLE
[Review] 서버에서 가져온 데이터를 화면에 보여주기

### ISSUE THREAD

**Issue by Jinsujin** [SangHwi-Back/todo-list#50]
> 아래 이슈가 반영된 PR에  Review 사항을 반영
- #23
- #24
- #27
- #28

## 📝 Tasks
- [x] gitignore에 .DS_Store 추가

### 1. CardsFetchingDataTask 수정
- [x] URLType 네이밍 변경
- [x] `toURL(type: URLType) -> URL?` 메서드에서 만들어둔 함수를 활용하기

### 2. 네이밍 수정
- [x] CoreDataManager를 보다 구체적인 역할이 드러나는 이름으로 수정
- [x] TodoTableViewManagement
- [x] `reloadAllLabels(_ card: CardData)`

### 3. dataSource 를 반영하는 메소드 검증 부분을 별도의 메소드로 변경
- [x] CardDataMiddleWare 의 dataSource 변수에 데이터를 저장하는 방식에 따라 set/insert 로 나누었습니다.
- [x] insert의 경우 dataSource 배열에 특정 인덱스 데이터만 바꾸는 것이기 때문에 인덱스를 검증하는 메소드가 필요했습니다.
       - 인덱스 검증 자체는 다른 역할을 한다고 판단하여 메소드를 분리하였습니다.

### 4. CardDataMiddleWare 를 테스트 가능하도록 변경
- [x] 고정값으로 반영하던 DataTask 역할의 변수를 초기화 메소드에서 주입할 수 있도록 하였습니다.
        - 주입방식은 클로저를 사용했습니다.
        - 이를 통해 기존의 DataTask 혹은 DebugDataTask 를 호출부에서 선택하여 사용할 수 있도록 하였습니다.
